#! /bin/bash
export AWS_CREDENTIAL_FILE=~/.ec2/awsCredentials
java -classpath lib/junit-4.5.jar:bin:lib/typica.jar:lib/jaxb-api.jar:lib/commons-httpclient-3.1.jar:lib/commons-logging-1.1.1.jar:lib/commons-codec-1.4.jar:lib/jaxb-impl.jar:lib/jsr173_1.0_api.jar:lib/activation.jar org.junit.runner.JUnitCore shlomo.ec2.elb.ELBSanityTest
